
#-----------------------------------------------------------------------

APP       := Test
TARGET    := TarsStressClient
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------
include /home/tarsproto/Test/TarsStressServer/TarsStressServer.mk
include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
