
#-----------------------------------------------------------------------

APP          := Test
TARGET       := TestPushServer
CONFIG       := 
STRIP_FLAG   := N
TARS2CPP_FLAG:= 

INCLUDE      += 
LIB          += 

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
