// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

var Ext = require('./Ext.js').Ext;
module.exports.Ext = Ext;

