/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttExtDomain.h"

@interface MttDomainRsp : TarsObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vDomain,setVDomain:)) NSArray* JV2_PROP_EX(r,0,vDomain,VONSString);
@property (nonatomic, assign, JV2_PROP_GS_V2(iDomainTime,setIDomainTime:)) TarsInt32 JV2_PROP_NM(r,1,iDomainTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(vStatUrl,setVStatUrl:)) NSArray* JV2_PROP_EX(o,2,vStatUrl,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vReportUrl,setVReportUrl:)) NSArray* JV2_PROP_EX(o,3,vReportUrl,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vLbsDomain,setVLbsDomain:)) NSArray* JV2_PROP_EX(o,4,vLbsDomain,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vExtDomain,setVExtDomain:)) NSArray* JV2_PROP_EX(o,5,vExtDomain,VOMTTExtDomain);

@end
