/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttEPushServerType.h"

#if TARSV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttEPushServerTypeHelper

+ (NSString *)etos:(MttEPushServerType)e
{
    switch(e){
        case MttEPushServerType_PUSH_MSGBOX: return @"MttEPushServerType_PUSH_MSGBOX";
        case MttEPushServerType_PUSH_MB: return @"MttEPushServerType_PUSH_MB";
        case MttEPushServerType_PUSH_HOTWORD: return @"MttEPushServerType_PUSH_HOTWORD";
        case MttEPushServerType_PUSH_ADS: return @"MttEPushServerType_PUSH_ADS";
        case MttEPushServerType_PUSH_BANNER: return @"MttEPushServerType_PUSH_BANNER";
        case MttEPushServerType_PUSH_HOMELAND: return @"MttEPushServerType_PUSH_HOMELAND";
        case MttEPushServerType_PUSH_MAIL: return @"MttEPushServerType_PUSH_MAIL";
        case MttEPushServerType_PUSH_WEATHER: return @"MttEPushServerType_PUSH_WEATHER";
        default: return @"";
    }
}

+ (MttEPushServerType)stoe:(NSString *)s
{
    if(isTarsEnumStringEqual(s, @"MttEPushServerType_PUSH_MSGBOX")) return MttEPushServerType_PUSH_MSGBOX;
    if(isTarsEnumStringEqual(s, @"MttEPushServerType_PUSH_MB")) return MttEPushServerType_PUSH_MB;
    if(isTarsEnumStringEqual(s, @"MttEPushServerType_PUSH_HOTWORD")) return MttEPushServerType_PUSH_HOTWORD;
    if(isTarsEnumStringEqual(s, @"MttEPushServerType_PUSH_ADS")) return MttEPushServerType_PUSH_ADS;
    if(isTarsEnumStringEqual(s, @"MttEPushServerType_PUSH_BANNER")) return MttEPushServerType_PUSH_BANNER;
    if(isTarsEnumStringEqual(s, @"MttEPushServerType_PUSH_HOMELAND")) return MttEPushServerType_PUSH_HOMELAND;
    if(isTarsEnumStringEqual(s, @"MttEPushServerType_PUSH_MAIL")) return MttEPushServerType_PUSH_MAIL;
    if(isTarsEnumStringEqual(s, @"MttEPushServerType_PUSH_WEATHER")) return MttEPushServerType_PUSH_WEATHER;
    return NSIntegerMin;
}

@end

#endif
