/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttEHotWordType.h"

#if TARSV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttEHotWordTypeHelper

+ (NSString *)etos:(MttEHotWordType)e
{
    switch(e){
        case MttEHotWordType_EHOTWORD_ALL: return @"MttEHotWordType_EHOTWORD_ALL";
        case MttEHotWordType_EHOTWORD_PAGE: return @"MttEHotWordType_EHOTWORD_PAGE";
        case MttEHotWordType_EHOTWORD_NOVEL: return @"MttEHotWordType_EHOTWORD_NOVEL";
        case MttEHotWordType_EHOTWORD_IMG: return @"MttEHotWordType_EHOTWORD_IMG";
        case MttEHotWordType_EHOTWORD_MUSIC: return @"MttEHotWordType_EHOTWORD_MUSIC";
        case MttEHotWordType_EHOTWORD_SOFT: return @"MttEHotWordType_EHOTWORD_SOFT";
        case MttEHotWordType_EHOTWORD_SHOP: return @"MttEHotWordType_EHOTWORD_SHOP";
        case MttEHotWordType_EHOTWORD_VIDEO: return @"MttEHotWordType_EHOTWORD_VIDEO";
        case MttEHotWordType_EHOTWORD_NEWS: return @"MttEHotWordType_EHOTWORD_NEWS";
        default: return @"";
    }
}

+ (MttEHotWordType)stoe:(NSString *)s
{
    if(isTarsEnumStringEqual(s, @"MttEHotWordType_EHOTWORD_ALL")) return MttEHotWordType_EHOTWORD_ALL;
    if(isTarsEnumStringEqual(s, @"MttEHotWordType_EHOTWORD_PAGE")) return MttEHotWordType_EHOTWORD_PAGE;
    if(isTarsEnumStringEqual(s, @"MttEHotWordType_EHOTWORD_NOVEL")) return MttEHotWordType_EHOTWORD_NOVEL;
    if(isTarsEnumStringEqual(s, @"MttEHotWordType_EHOTWORD_IMG")) return MttEHotWordType_EHOTWORD_IMG;
    if(isTarsEnumStringEqual(s, @"MttEHotWordType_EHOTWORD_MUSIC")) return MttEHotWordType_EHOTWORD_MUSIC;
    if(isTarsEnumStringEqual(s, @"MttEHotWordType_EHOTWORD_SOFT")) return MttEHotWordType_EHOTWORD_SOFT;
    if(isTarsEnumStringEqual(s, @"MttEHotWordType_EHOTWORD_SHOP")) return MttEHotWordType_EHOTWORD_SHOP;
    if(isTarsEnumStringEqual(s, @"MttEHotWordType_EHOTWORD_VIDEO")) return MttEHotWordType_EHOTWORD_VIDEO;
    if(isTarsEnumStringEqual(s, @"MttEHotWordType_EHOTWORD_NEWS")) return MttEHotWordType_EHOTWORD_NEWS;
    return NSIntegerMin;
}

@end

#endif
