/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttErrorCode.h"

#if TARSV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttErrorCodeHelper

+ (NSString *)etos:(MttErrorCode)e
{
    switch(e){
        case MttErrorCode_ERROR_PROTOCOL: return @"MttErrorCode_ERROR_PROTOCOL";
        case MttErrorCode_ERROR_REFUSE_REQUEST: return @"MttErrorCode_ERROR_REFUSE_REQUEST";
        case MttErrorCode_ERROR_UNSUPPORTED_VERSION: return @"MttErrorCode_ERROR_UNSUPPORTED_VERSION";
        default: return @"";
    }
}

+ (MttErrorCode)stoe:(NSString *)s
{
    if(isTarsEnumStringEqual(s, @"MttErrorCode_ERROR_PROTOCOL")) return MttErrorCode_ERROR_PROTOCOL;
    if(isTarsEnumStringEqual(s, @"MttErrorCode_ERROR_REFUSE_REQUEST")) return MttErrorCode_ERROR_REFUSE_REQUEST;
    if(isTarsEnumStringEqual(s, @"MttErrorCode_ERROR_UNSUPPORTED_VERSION")) return MttErrorCode_ERROR_UNSUPPORTED_VERSION;
    return NSIntegerMin;
}

@end

#endif
