/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttPageConfigReq.h"

@implementation MttPageConfigReq

@synthesize JV2_PROP_NM(r,0,stUserBase);
@synthesize JV2_PROP_NM(r,1,stBrowserReq);
@synthesize JV2_PROP_NM(r,2,stSearchReq);
@synthesize JV2_PROP_NM(r,3,stStaticConfigReq);
@synthesize JV2_PROP_NM(o,4,stSearchTypeReq);
@synthesize JV2_PROP_NM(o,5,stLPageReq);
@synthesize JV2_PROP_NM(o,6,stCityListReq);

+ (void)initialize
{
    if (self == [MttPageConfigReq class]) {
        [MttCityListReq initialize];
        [MttLPageReq initialize];
        [MttPageBrowserReq initialize];
        [MttSearchReq initialize];
        [MttSearchTypeReq initialize];
        [MttStaticConfigReq initialize];
        [MttUserBase initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(stUserBase) = [MttUserBase object];
        JV2_PROP(stBrowserReq) = [MttPageBrowserReq object];
        JV2_PROP(stSearchReq) = [MttSearchReq object];
        JV2_PROP(stStaticConfigReq) = [MttStaticConfigReq object];
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(stUserBase) = nil;
    JV2_PROP(stBrowserReq) = nil;
    JV2_PROP(stSearchReq) = nil;
    JV2_PROP(stStaticConfigReq) = nil;
    JV2_PROP(stSearchTypeReq) = nil;
    JV2_PROP(stLPageReq) = nil;
    JV2_PROP(stCityListReq) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.PageConfigReq";
}

@end
