/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttImageQuality.h"
#import "MttMethod.h"
#import "MttSTImagePolicy.h"
#import "MttSTJSInfo.h"
#import "MttSTSpeedStatis.h"
#import "MttUserBase.h"

@interface MttRelayPageReq : TarsObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(stUB,setStUB:)) MttUserBase* JV2_PROP_NM(r,0,stUB);
@property (nonatomic, assign, JV2_PROP_GS_V2(eMethod,setEMethod:)) MttMethod JV2_PROP_NM(r,1,eMethod);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUrl,setSUrl:)) NSString* JV2_PROP_NM(r,2,sUrl);
@property (nonatomic, retain, JV2_PROP_GS_V2(sReferer,setSReferer:)) NSString* JV2_PROP_NM(o,3,sReferer);
@property (nonatomic, retain, JV2_PROP_GS_V2(sExtraHeader,setSExtraHeader:)) NSString* JV2_PROP_NM(r,4,sExtraHeader);
@property (nonatomic, retain, JV2_PROP_GS_V2(vPostData,setVPostData:)) NSData* JV2_PROP_NM(o,5,vPostData);
@property (nonatomic, retain, JV2_PROP_GS_V2(sPageOrigEncode,setSPageOrigEncode:)) NSString* JV2_PROP_NM(r,6,sPageOrigEncode);
@property (nonatomic, assign, JV2_PROP_GS_V2(iPageSizeKB,setIPageSizeKB:)) TarsInt32 JV2_PROP_NM(r,7,iPageSizeKB);
@property (nonatomic, retain, JV2_PROP_GS_V2(vLocalPicHash,setVLocalPicHash:)) NSArray* JV2_PROP_EX(r,8,vLocalPicHash,VONSNumber);
@property (nonatomic, assign, JV2_PROP_GS_V2(eQualityType,setEQualityType:)) MttImageQuality JV2_PROP_NM(r,9,eQualityType);
@property (nonatomic, assign, JV2_PROP_GS_V2(iWidth,setIWidth:)) TarsInt32 JV2_PROP_NM(r,10,iWidth);
@property (nonatomic, assign, JV2_PROP_GS_V2(iHeight,setIHeight:)) TarsInt32 JV2_PROP_NM(r,11,iHeight);
@property (nonatomic, retain, JV2_PROP_GS_V2(sTSpeed,setSTSpeed:)) MttSTSpeedStatis* JV2_PROP_NM(r,12,sTSpeed);
@property (nonatomic, retain, JV2_PROP_GS_V2(stImgPolicy,setStImgPolicy:)) MttSTImagePolicy* JV2_PROP_NM(o,13,stImgPolicy);
@property (nonatomic, retain, JV2_PROP_GS_V2(stJSInfo,setStJSInfo:)) MttSTJSInfo* JV2_PROP_NM(o,14,stJSInfo);

@end
