/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016 THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.qq.tars.support.config.prx;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

/**
 * config obj to load server's system config.
 **/
public abstract class ConfigPrxCallback extends TarsAbstractCallback {

	public abstract void callback_ListConfig(int ret, java.util.List<String> vf);

	public abstract void callback_loadConfig(int ret, String config);

	public abstract void callback_loadConfigByHost(int ret, String config);

	public abstract void callback_checkConfig(int ret, String result);

	public abstract void callback_ListConfigByInfo(int ret, java.util.List<String> vf);

	public abstract void callback_loadConfigByInfo(int ret, String config);

	public abstract void callback_checkConfigByInfo(int ret, String result);

}
