// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

var tars = require('./NodeTars.js').tars;
module.exports.tars = tars;

tars.NodeTarsImp.prototype.initialize = function ( ) {
    //TODO::
    console.log(" NodeTarsImp initialized ")
}

tars.NodeTarsImp.prototype.test = function (current) {
    //TODO::

}

tars.NodeTarsImp.prototype.getall = function (current, stUser, stResult) {
    //TODO::
    console.log("stUser.name::", stUser.name);
    stResult.iLevel = 11000;
    current.sendResponse(10000, stResult);
}

tars.NodeTarsImp.prototype.getUsrName = function (current, sUsrName, sValue1, sValue2) {
    //TODO::
    console.log("sUsrName::", sUsrName);
    sValue1 = "OUT_" + sUsrName + "_1";
    sValue2 = "OUT_" + sUsrName + "_2";
    current.sendResponse(100002, sValue1, sValue2);
}


