<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__login.proto

namespace Proto\yb_account\account__login;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>out</code>
 */
class out extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     *渠道
     *
     * Generated from protobuf field <code>string regChannel = 2;</code>
     */
    private $regChannel = '';
    /**
     *wx_openid
     *
     * Generated from protobuf field <code>string wxOpenid = 3;</code>
     */
    private $wxOpenid = '';

    public function __construct() {
        \GPBMetadata\YbAccount\AccountLogin::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     *渠道
     *
     * Generated from protobuf field <code>string regChannel = 2;</code>
     * @return string
     */
    public function getRegChannel()
    {
        return $this->regChannel;
    }

    /**
     *渠道
     *
     * Generated from protobuf field <code>string regChannel = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRegChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->regChannel = $var;

        return $this;
    }

    /**
     *wx_openid
     *
     * Generated from protobuf field <code>string wxOpenid = 3;</code>
     * @return string
     */
    public function getWxOpenid()
    {
        return $this->wxOpenid;
    }

    /**
     *wx_openid
     *
     * Generated from protobuf field <code>string wxOpenid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setWxOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->wxOpenid = $var;

        return $this;
    }

}

