
#-----------------------------------------------------------------------

APP       := TestApp
TARGET    := HttpServer
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------i

include /usr/local/tars/cpp/makefile/makefile.tars
