
#-----------------------------------------------------------------------
APP       := Test
TARGET    := myClientPromise
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   +=

#-----------------------------------------------------------------------
include /home/tarsproto/Test/AServer/AServer.mk
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
