/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttBrokerSimplifiedPushResponse.h"

@implementation MttBrokerSimplifiedPushResponse

@synthesize JV2_PROP_NM(o,0,iPushTime);
@synthesize JV2_PROP_EX(o,1,wAppId,VONSNumber);
@synthesize JV2_PROP_EX(o,2,wTabId,VONSNumber);
@synthesize JV2_PROP_EX(o,3,wWaitPushTime,VONSNumber);
@synthesize JV2_PROP_NM(o,4,cType);
@synthesize JV2_PROP_EX(o,5,vContent,VONSData);
@synthesize JV2_PROP_EX(o,6,wStatusCode,VONSNumber);
@synthesize JV2_PROP_EX(o,7,imglist,M09ONSStringONSData);

+ (void)initialize
{
    if (self == [MttBrokerSimplifiedPushResponse class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(wAppId) = nil;
    JV2_PROP(wTabId) = nil;
    JV2_PROP(wWaitPushTime) = nil;
    JV2_PROP(cType) = nil;
    JV2_PROP(vContent) = nil;
    JV2_PROP(wStatusCode) = nil;
    JV2_PROP(imglist) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.BrokerSimplifiedPushResponse";
}

@end
