/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttBrokerUserInfo.h"

@implementation MttBrokerUserInfo

@synthesize JV2_PROP_NM(r,0,sGUID);
@synthesize JV2_PROP_NM(r,1,sQUA);
@synthesize JV2_PROP_NM(r,2,sLC);
@synthesize JV2_PROP_NM(r,3,sIMEI);
@synthesize JV2_PROP_NM(r,4,sSession);
@synthesize JV2_PROP_NM(r,5,wTabId);
@synthesize JV2_PROP_NM(o,6,sIMSI);
@synthesize JV2_PROP_NM(o,7,sCellid);
@synthesize JV2_PROP_NM(o,8,sLAC);
@synthesize JV2_PROP_NM(o,9,sAPN);
@synthesize JV2_PROP_NM(o,10,sChannelId);
@synthesize JV2_PROP_NM(o,11,sUin);
@synthesize JV2_PROP_NM(o,12,sUserSession);
@synthesize JV2_PROP_NM(o,13,cStoreAbility);
@synthesize JV2_PROP_NM(o,14,iLanguageType);
@synthesize JV2_PROP_NM(o,15,iMCC);
@synthesize JV2_PROP_NM(o,16,iMNC);
@synthesize JV2_PROP_NM(o,17,cARMV7);

+ (void)initialize
{
    if (self == [MttBrokerUserInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sGUID) = DefaultTarsData;
        JV2_PROP(sQUA) = DefaultTarsString;
        JV2_PROP(sLC) = DefaultTarsString;
        JV2_PROP(sIMEI) = DefaultTarsString;
        JV2_PROP(sSession) = DefaultTarsString;
        JV2_PROP(sIMSI) = DefaultTarsString;
        JV2_PROP(sCellid) = DefaultTarsString;
        JV2_PROP(sLAC) = DefaultTarsString;
        JV2_PROP(sAPN) = DefaultTarsString;
        JV2_PROP(sChannelId) = DefaultTarsString;
        JV2_PROP(sUin) = DefaultTarsString;
        JV2_PROP(sUserSession) = DefaultTarsString;
        JV2_PROP(cStoreAbility) = 1;
        JV2_PROP(iLanguageType) = 200;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sGUID) = nil;
    JV2_PROP(sQUA) = nil;
    JV2_PROP(sLC) = nil;
    JV2_PROP(sIMEI) = nil;
    JV2_PROP(sSession) = nil;
    JV2_PROP(sIMSI) = nil;
    JV2_PROP(sCellid) = nil;
    JV2_PROP(sLAC) = nil;
    JV2_PROP(sAPN) = nil;
    JV2_PROP(sChannelId) = nil;
    JV2_PROP(sUin) = nil;
    JV2_PROP(sUserSession) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.BrokerUserInfo";
}

@end
