/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttBrokerSimplifiedRequest.h"

@implementation MttBrokerSimplifiedRequest

@synthesize JV2_PROP_NM(o,0,requestType);
@synthesize JV2_PROP_NM(o,1,sGUID);
@synthesize JV2_PROP_NM(o,2,sQUA);
@synthesize JV2_PROP_NM(o,3,sLC);
@synthesize JV2_PROP_NM(o,4,sSession);
@synthesize JV2_PROP_NM(o,5,wTabId);
@synthesize JV2_PROP_NM(o,6,sChannelId);
@synthesize JV2_PROP_NM(o,10,wScreenWidth);
@synthesize JV2_PROP_NM(o,11,wScreenHeight);
@synthesize JV2_PROP_NM(o,12,cFontSize);
@synthesize JV2_PROP_NM(o,13,cRowSpacing);
@synthesize JV2_PROP_NM(o,14,vCharSetKey);
@synthesize JV2_PROP_NM(o,15,cSupportedImage);
@synthesize JV2_PROP_NM(o,20,wVersion);
@synthesize JV2_PROP_NM(o,21,sUrl);
@synthesize JV2_PROP_NM(o,22,sUserHttpHeader);
@synthesize JV2_PROP_NM(o,23,sPageEncodeName);
@synthesize JV2_PROP_NM(o,24,cZipType);
@synthesize JV2_PROP_NM(o,25,cImgQualityType);
@synthesize JV2_PROP_NM(o,26,wPageSizeKB);
@synthesize JV2_PROP_EX(o,27,vImgCacheFNV,VONSNumber);
@synthesize JV2_PROP_NM(o,28,cLzmaDictOffset);
@synthesize JV2_PROP_NM(o,29,iEntry);
@synthesize JV2_PROP_NM(o,30,iEntryType);
@synthesize JV2_PROP_NM(o,31,cSecuritySwitch);
@synthesize JV2_PROP_NM(o,40,vPostData);
@synthesize JV2_PROP_NM(o,41,cJSEvent);
@synthesize JV2_PROP_NM(o,42,iJSNode);
@synthesize JV2_PROP_EX(o,43,viKey,VONSNumber);
@synthesize JV2_PROP_EX(o,44,vvbValue,VONSData);
@synthesize JV2_PROP_NM(o,50,sUpBoundary);
@synthesize JV2_PROP_NM(o,51,sUpContentType);
@synthesize JV2_PROP_NM(o,52,sUpFileName);
@synthesize JV2_PROP_NM(o,53,sUpName);
@synthesize JV2_PROP_NM(o,54,cUpZipType);
@synthesize JV2_PROP_NM(o,55,iUpFileSize);
@synthesize JV2_PROP_NM(o,56,iUpPackNo);
@synthesize JV2_PROP_NM(o,57,iUpDataSize);
@synthesize JV2_PROP_NM(o,58,cUpNeedResponse);
@synthesize JV2_PROP_NM(o,59,cStoreAbility);
@synthesize JV2_PROP_NM(o,60,iLanguageType);
@synthesize JV2_PROP_NM(o,61,cContentType);
@synthesize JV2_PROP_NM(o,62,cReqEncrypted);

+ (void)initialize
{
    if (self == [MttBrokerSimplifiedRequest class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sQUA) = DefaultTarsString;
        JV2_PROP(sLC) = DefaultTarsString;
        JV2_PROP(sSession) = DefaultTarsString;
        JV2_PROP(sChannelId) = DefaultTarsString;
        JV2_PROP(wScreenWidth) = 240;
        JV2_PROP(wScreenHeight) = 320;
        JV2_PROP(wVersion) = 1;
        JV2_PROP(sUrl) = DefaultTarsString;
        JV2_PROP(sUserHttpHeader) = DefaultTarsString;
        JV2_PROP(sPageEncodeName) = DefaultTarsString;
        JV2_PROP(cZipType) = 1;
        JV2_PROP(cImgQualityType) = 3;
        JV2_PROP(wPageSizeKB) = 50;
        JV2_PROP(cLzmaDictOffset) = 17;
        JV2_PROP(iEntryType) = 6;
        JV2_PROP(sUpBoundary) = DefaultTarsString;
        JV2_PROP(sUpContentType) = DefaultTarsString;
        JV2_PROP(sUpFileName) = DefaultTarsString;
        JV2_PROP(sUpName) = DefaultTarsString;
        JV2_PROP(cStoreAbility) = 1;
        JV2_PROP(iLanguageType) = 200;
        JV2_PROP(cContentType) = 4;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sGUID) = nil;
    JV2_PROP(sQUA) = nil;
    JV2_PROP(sLC) = nil;
    JV2_PROP(sSession) = nil;
    JV2_PROP(sChannelId) = nil;
    JV2_PROP(vCharSetKey) = nil;
    JV2_PROP(sUrl) = nil;
    JV2_PROP(sUserHttpHeader) = nil;
    JV2_PROP(sPageEncodeName) = nil;
    JV2_PROP(vImgCacheFNV) = nil;
    JV2_PROP(vPostData) = nil;
    JV2_PROP(viKey) = nil;
    JV2_PROP(vvbValue) = nil;
    JV2_PROP(sUpBoundary) = nil;
    JV2_PROP(sUpContentType) = nil;
    JV2_PROP(sUpFileName) = nil;
    JV2_PROP(sUpName) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.BrokerSimplifiedRequest";
}

@end
