/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttBrokerRequestParam.h"

@implementation MttBrokerRequestParam

@synthesize JV2_PROP_NM(r,0,cConcurrency);
@synthesize JV2_PROP_NM(r,1,sUrl);
@synthesize JV2_PROP_NM(r,2,sUserHttpHeader);
@synthesize JV2_PROP_NM(r,3,sPageEncodeName);
@synthesize JV2_PROP_NM(r,4,cZipType);
@synthesize JV2_PROP_NM(o,5,cContentType);
@synthesize JV2_PROP_NM(o,6,cPostEncrypted);
@synthesize JV2_PROP_NM(o,7,cImgQualityType);
@synthesize JV2_PROP_NM(o,8,wPageSizeKB);
@synthesize JV2_PROP_NM(o,9,wMaxPageSizeKB);
@synthesize JV2_PROP_NM(o,10,cBrand);
@synthesize JV2_PROP_NM(o,11,stDisplayInfo);
@synthesize JV2_PROP_EX(o,12,vImgCacheFNV,VONSNumber);
@synthesize JV2_PROP_NM(o,13,iEntry);
@synthesize JV2_PROP_NM(o,14,iEntryType);
@synthesize JV2_PROP_NM(o,15,cReqEncrypted);
@synthesize JV2_PROP_NM(o,16,wVersion);
@synthesize JV2_PROP_NM(o,17,cHttpsForceProxy);
@synthesize JV2_PROP_NM(o,18,cLzmaDictOffset);
@synthesize JV2_PROP_NM(o,19,cReqType);
@synthesize JV2_PROP_NM(o,20,stPushReq);
@synthesize JV2_PROP_NM(o,21,cSecuritySwitch);
@synthesize JV2_PROP_NM(o,22,cReqOriginalPage);

+ (void)initialize
{
    if (self == [MttBrokerRequestParam class]) {
        [MttBrokerDisplayInfo initialize];
        [MttBrokerPushRequest initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sUrl) = DefaultTarsString;
        JV2_PROP(sUserHttpHeader) = DefaultTarsString;
        JV2_PROP(sPageEncodeName) = DefaultTarsString;
        JV2_PROP(cImgQualityType) = 3;
        JV2_PROP(wPageSizeKB) = 50;
        JV2_PROP(wMaxPageSizeKB) = 200;
        JV2_PROP(iEntryType) = 6;
        JV2_PROP(wVersion) = 1;
        JV2_PROP(cLzmaDictOffset) = 17;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sUrl) = nil;
    JV2_PROP(sUserHttpHeader) = nil;
    JV2_PROP(sPageEncodeName) = nil;
    JV2_PROP(stDisplayInfo) = nil;
    JV2_PROP(vImgCacheFNV) = nil;
    JV2_PROP(stPushReq) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.BrokerRequestParam";
}

@end
