/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"

@interface MttBrokerSimplifiedPushRequest : TarsObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(requestType,setRequestType:)) TarsInt8 JV2_PROP_NM(o,0,requestType);
@property (nonatomic, retain, JV2_PROP_GS_V2(sGUID,setSGUID:)) NSData* JV2_PROP_NM(o,1,sGUID);
@property (nonatomic, retain, JV2_PROP_GS_V2(sQUA,setSQUA:)) NSString* JV2_PROP_NM(o,2,sQUA);
@property (nonatomic, retain, JV2_PROP_GS_V2(sLC,setSLC:)) NSString* JV2_PROP_NM(o,3,sLC);
@property (nonatomic, retain, JV2_PROP_GS_V2(sSession,setSSession:)) NSString* JV2_PROP_NM(o,4,sSession);
@property (nonatomic, assign, JV2_PROP_GS_V2(wTabId,setWTabId:)) TarsInt16 JV2_PROP_NM(o,5,wTabId);
@property (nonatomic, retain, JV2_PROP_GS_V2(sChannelId,setSChannelId:)) NSString* JV2_PROP_NM(o,6,sChannelId);
@property (nonatomic, retain, JV2_PROP_GS_V2(strCookie,setStrCookie:)) NSString* JV2_PROP_NM(o,11,strCookie);
@property (nonatomic, assign, JV2_PROP_GS_V2(iPushTime,setIPushTime:)) TarsInt32 JV2_PROP_NM(r,12,iPushTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(vPushAppReqId,setVPushAppReqId:)) NSArray* JV2_PROP_EX(r,13,vPushAppReqId,VONSNumber);
@property (nonatomic, retain, JV2_PROP_GS_V2(vdata,setVdata:)) NSArray* JV2_PROP_EX(o,14,vdata,VONSData);
@property (nonatomic, assign, JV2_PROP_GS_V2(wVersion,setWVersion:)) TarsInt16 JV2_PROP_NM(o,15,wVersion);
@property (nonatomic, assign, JV2_PROP_GS_V2(cFontSize,setCFontSize:)) TarsInt8 JV2_PROP_NM(o,16,cFontSize);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetKey,setVCharSetKey:)) NSData* JV2_PROP_NM(o,17,vCharSetKey);
@property (nonatomic, assign, JV2_PROP_GS_V2(wScreenWidth,setWScreenWidth:)) TarsInt16 JV2_PROP_NM(o,18,wScreenWidth);
@property (nonatomic, assign, JV2_PROP_GS_V2(wScreenHeight,setWScreenHeight:)) TarsInt16 JV2_PROP_NM(o,19,wScreenHeight);

@end
