/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"

enum {
    MttEDomainType_InnerDomain = 0,
    MttEDomainType_StatUrl = 1,
    MttEDomainType_ReportUrl = 2,
    MttEDomainType_LbsUrl = 3,
    MttEDomainType_ReadModel = 4,
    MttEDomainType_NovelModel = 5,
    MttEDomainType_NetDisk = 6,
    MttEDomainType_MsgBox = 7,
    MttEDomainType_BookMarks = 8,
    MttEDomainType_UserCenter = 9,
    MttEDomainType_MicroBlogTextShare = 10,
    MttEDomainType_MicroBlogPicShare = 11,
    MttEDomainType_ReqBroker = 12,
    MttEDomainType_WebkitModel = 13,
    MttEDomainType_ACPortal = 14,
    MttEDomainType_DownLoadAddr = 15,
    MttEDomainType_InfoCenter = 16,
    MttEDomainType_NovelCenter = 17,
    MttEDomainType_SMSAddr = 18,
    MttEDomainType_SafeWhiteList = 19,
    MttEDomainType_SafeReport = 20,
    MttEDomainType_DirectWap = 21,
    MttEDomainType_SaveToNetDisk = 22,
    MttEDomainType_KjavaMiniHelp = 23,
    MttEDomainType_AliPayWhiteList = 24,
    MttEDomainType_MttModel4ADR = 25,
    MttEDomainType_MttRegexModel4ADR = 26,
    MttEDomainType_WebkitRegexModel4ADR = 27,
    MttEDomainType_WebkitModel4ADR = 28,
    MttEDomainType_SimpleWindow = 29,
    MttEDomainType_SafeWhiteList4IPAD = 30,
    MttEDomainType_AdsPush = 31,
    MttEDomainType_MTTModel4Iphone = 32,
    MttEDomainType_MTTRegexModel4Iphone = 33,
    MttEDomainType_WebkitModel4Iphone = 34,
    MttEDomainType_WebkitRegexModel4Iphone = 35,
    MttEDomainType_ChangeCityUrl = 36,
    MttEDomainType_NetNoteUrl = 37,
    MttEDomainType_Upload2NetDiskUrl = 38,
    MttEDomainType_DownloadNetDiskUrl = 39,
    MttEDomainType_HotWordUrl1 = 40,
    MttEDomainType_HotWordUrl2 = 41,
    MttEDomainType_NeedQProxy = 42,
    MttEDomainType_PerformanceStatUrl = 43,
    MttEDomainType_WebkitModelExt25 = 99
};
#define MttEDomainType NSInteger

#if TARSV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface MttEDomainTypeHelper: TarsEnumHelper

+ (NSString *)etos:(MttEDomainType)e;
+ (MttEDomainType)stoe:(NSString *)s;

@end

#endif
