/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttEUSESTAT.h"

#if TARSV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttEUSESTATHelper

+ (NSString *)etos:(MttEUSESTAT)e
{
    switch(e){
        case MttEUSESTAT_NAVIGATION: return @"MttEUSESTAT_NAVIGATION";
        case MttEUSESTAT_UPDATE: return @"MttEUSESTAT_UPDATE";
        case MttEUSESTAT_ZONE: return @"MttEUSESTAT_ZONE";
        case MttEUSESTAT_MAIL: return @"MttEUSESTAT_MAIL";
        case MttEUSESTAT_CHAT: return @"MttEUSESTAT_CHAT";
        case MttEUSESTAT_UOTHER: return @"MttEUSESTAT_UOTHER";
        default: return @"";
    }
}

+ (MttEUSESTAT)stoe:(NSString *)s
{
    if(isTarsEnumStringEqual(s, @"MttEUSESTAT_NAVIGATION")) return MttEUSESTAT_NAVIGATION;
    if(isTarsEnumStringEqual(s, @"MttEUSESTAT_UPDATE")) return MttEUSESTAT_UPDATE;
    if(isTarsEnumStringEqual(s, @"MttEUSESTAT_ZONE")) return MttEUSESTAT_ZONE;
    if(isTarsEnumStringEqual(s, @"MttEUSESTAT_MAIL")) return MttEUSESTAT_MAIL;
    if(isTarsEnumStringEqual(s, @"MttEUSESTAT_CHAT")) return MttEUSESTAT_CHAT;
    if(isTarsEnumStringEqual(s, @"MttEUSESTAT_UOTHER")) return MttEUSESTAT_UOTHER;
    return NSIntegerMin;
}

@end

#endif
