/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"

enum {
    MttEServerVer_AUTOSIZE = 2,
    MttEServerVer_NOKIAJAVA = 3,
    MttEServerVer_NOKIASYM = 4,
    MttEServerVer_NOKIASMBV5 = 5,
    MttEServerVer_LITE = 6,
    MttEServerVer_NOKIAITEM2 = 7,
    MttEServerVer_TELBREW = 8,
    MttEServerVer_TELANDROID = 9,
    MttEServerVer_IPAD = 10,
    MttEServerVer_IPAD2 = 11,
    MttEServerVer_UINCOM = 12,
    MttEServerVer_NOKIA = 13,
    MttEServerVer_JIGUANG = 14,
    MttEServerVer_GMCC = 15,
    MttEServerVer_APAD = 16,
    MttEServerVer_TELECOM = 17
};
#define MttEServerVer NSInteger

#if TARSV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface MttEServerVerHelper: TarsEnumHelper

+ (NSString *)etos:(MttEServerVer)e;
+ (MttEServerVer)stoe:(NSString *)s;

@end

#endif
