/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttEEntryType.h"

#if TARSV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttEEntryTypeHelper

+ (NSString *)etos:(MttEEntryType)e
{
    switch(e){
        case MttEEntryType_STARTLINK: return @"MttEEntryType_STARTLINK";
        case MttEEntryType_INPUTADDR: return @"MttEEntryType_INPUTADDR";
        case MttEEntryType_BOOKMARK: return @"MttEEntryType_BOOKMARK";
        case MttEEntryType_HISTORY: return @"MttEEntryType_HISTORY";
        case MttEEntryType_OFTENUSE: return @"MttEEntryType_OFTENUSE";
        case MttEEntryType_FASTLINK: return @"MttEEntryType_FASTLINK";
        case MttEEntryType_OTHER: return @"MttEEntryType_OTHER";
        case MttEEntryType_ESEARCH: return @"MttEEntryType_ESEARCH";
        case MttEEntryType_HOTWORD: return @"MttEEntryType_HOTWORD";
        case MttEEntryType_APPCENTER: return @"MttEEntryType_APPCENTER";
        case MttEEntryType_FASTLINKCONF: return @"MttEEntryType_FASTLINKCONF";
        default: return @"";
    }
}

+ (MttEEntryType)stoe:(NSString *)s
{
    if(isTarsEnumStringEqual(s, @"MttEEntryType_STARTLINK")) return MttEEntryType_STARTLINK;
    if(isTarsEnumStringEqual(s, @"MttEEntryType_INPUTADDR")) return MttEEntryType_INPUTADDR;
    if(isTarsEnumStringEqual(s, @"MttEEntryType_BOOKMARK")) return MttEEntryType_BOOKMARK;
    if(isTarsEnumStringEqual(s, @"MttEEntryType_HISTORY")) return MttEEntryType_HISTORY;
    if(isTarsEnumStringEqual(s, @"MttEEntryType_OFTENUSE")) return MttEEntryType_OFTENUSE;
    if(isTarsEnumStringEqual(s, @"MttEEntryType_FASTLINK")) return MttEEntryType_FASTLINK;
    if(isTarsEnumStringEqual(s, @"MttEEntryType_OTHER")) return MttEEntryType_OTHER;
    if(isTarsEnumStringEqual(s, @"MttEEntryType_ESEARCH")) return MttEEntryType_ESEARCH;
    if(isTarsEnumStringEqual(s, @"MttEEntryType_HOTWORD")) return MttEEntryType_HOTWORD;
    if(isTarsEnumStringEqual(s, @"MttEEntryType_APPCENTER")) return MttEEntryType_APPCENTER;
    if(isTarsEnumStringEqual(s, @"MttEEntryType_FASTLINKCONF")) return MttEEntryType_FASTLINKCONF;
    return NSIntegerMin;
}

@end

#endif
