/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttImageQuality.h"

#if TARSV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttImageQualityHelper

+ (NSString *)etos:(MttImageQuality)e
{
    switch(e){
        case MttImageQuality_QUALITY_NONE: return @"MttImageQuality_QUALITY_NONE";
        case MttImageQuality_QUALITY_MINI: return @"MttImageQuality_QUALITY_MINI";
        case MttImageQuality_QUALITY_LOW: return @"MttImageQuality_QUALITY_LOW";
        case MttImageQuality_QUALITY_STANDARD: return @"MttImageQuality_QUALITY_STANDARD";
        case MttImageQuality_QUALITY_HIGH: return @"MttImageQuality_QUALITY_HIGH";
        case MttImageQuality_QUALITY_SUPER: return @"MttImageQuality_QUALITY_SUPER";
        case MttImageQuality_QUALITY_ORIGIN: return @"MttImageQuality_QUALITY_ORIGIN";
        default: return @"";
    }
}

+ (MttImageQuality)stoe:(NSString *)s
{
    if(isTarsEnumStringEqual(s, @"MttImageQuality_QUALITY_NONE")) return MttImageQuality_QUALITY_NONE;
    if(isTarsEnumStringEqual(s, @"MttImageQuality_QUALITY_MINI")) return MttImageQuality_QUALITY_MINI;
    if(isTarsEnumStringEqual(s, @"MttImageQuality_QUALITY_LOW")) return MttImageQuality_QUALITY_LOW;
    if(isTarsEnumStringEqual(s, @"MttImageQuality_QUALITY_STANDARD")) return MttImageQuality_QUALITY_STANDARD;
    if(isTarsEnumStringEqual(s, @"MttImageQuality_QUALITY_HIGH")) return MttImageQuality_QUALITY_HIGH;
    if(isTarsEnumStringEqual(s, @"MttImageQuality_QUALITY_SUPER")) return MttImageQuality_QUALITY_SUPER;
    if(isTarsEnumStringEqual(s, @"MttImageQuality_QUALITY_ORIGIN")) return MttImageQuality_QUALITY_ORIGIN;
    return NSIntegerMin;
}

@end

#endif
