/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttImageQuality.h"
#import "MttSTSpeedStatis.h"
#import "MttUserBase.h"

@interface MttImageReq : TarsObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(stUB,setStUB:)) MttUserBase* JV2_PROP_NM(r,0,stUB);
@property (nonatomic, assign, JV2_PROP_GS_V2(eQualityType,setEQualityType:)) MttImageQuality JV2_PROP_NM(r,1,eQualityType);
@property (nonatomic, assign, JV2_PROP_GS_V2(iWidth,setIWidth:)) TarsInt32 JV2_PROP_NM(r,2,iWidth);
@property (nonatomic, assign, JV2_PROP_GS_V2(iHeight,setIHeight:)) TarsInt32 JV2_PROP_NM(r,3,iHeight);
@property (nonatomic, retain, JV2_PROP_GS_V2(vPicURLList,setVPicURLList:)) NSArray* JV2_PROP_EX(r,4,vPicURLList,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(sReferer,setSReferer:)) NSString* JV2_PROP_NM(o,5,sReferer);
@property (nonatomic, retain, JV2_PROP_GS_V2(sExtraHeader,setSExtraHeader:)) NSString* JV2_PROP_NM(r,6,sExtraHeader);
@property (nonatomic, retain, JV2_PROP_GS_V2(sTSpeed,setSTSpeed:)) MttSTSpeedStatis* JV2_PROP_NM(r,7,sTSpeed);

@end
