/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttLoginRsp.h"

@implementation MttLoginRsp

@synthesize JV2_PROP_NM(r,0,sGUID);
@synthesize JV2_PROP_NM(r,1,vAuth);
@synthesize JV2_PROP_NM(r,2,iTime);
@synthesize JV2_PROP_EX(r,3,vProxyList,VONSString);
@synthesize JV2_PROP_EX(r,4,vRelayList,VONSString);
@synthesize JV2_PROP_NM(r,5,stUpdateRsp);
@synthesize JV2_PROP_NM(o,6,stVerifyRspExt);
@synthesize JV2_PROP_NM(o,7,iStatValue);
@synthesize JV2_PROP_NM(o,8,vRelayHttpsList);
@synthesize JV2_PROP_NM(o,10,vCharSetKey);
@synthesize JV2_PROP_NM(o,11,vMidCharSetKey);
@synthesize JV2_PROP_NM(o,12,vBigCharSetKey);
@synthesize JV2_PROP_EX(o,13,vCharSetMD5Group,VOMTTSTSingleMD5);
@synthesize JV2_PROP_NM(o,14,iHttpProxySession);
@synthesize JV2_PROP_EX(o,15,vQProxyList,VONSString);
@synthesize JV2_PROP_NM(o,16,cProtocolFlag);

+ (void)initialize
{
    if (self == [MttLoginRsp class]) {
        [MttSTSingleMD5 initialize];
        [MttUpdateRsp initialize];
        [MttVerifyRspExt initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sGUID) = DefaultTarsData;
        JV2_PROP(vAuth) = DefaultTarsData;
        JV2_PROP(vProxyList) = DefaultTarsArray;
        JV2_PROP(vRelayList) = DefaultTarsArray;
        JV2_PROP(stUpdateRsp) = [MttUpdateRsp object];
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sGUID) = nil;
    JV2_PROP(vAuth) = nil;
    JV2_PROP(vProxyList) = nil;
    JV2_PROP(vRelayList) = nil;
    JV2_PROP(stUpdateRsp) = nil;
    JV2_PROP(stVerifyRspExt) = nil;
    JV2_PROP(vRelayHttpsList) = nil;
    JV2_PROP(vCharSetKey) = nil;
    JV2_PROP(vMidCharSetKey) = nil;
    JV2_PROP(vBigCharSetKey) = nil;
    JV2_PROP(vCharSetMD5Group) = nil;
    JV2_PROP(vQProxyList) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.LoginRsp";
}

@end
