/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttERelayProtoVer.h"
#import "MttSTSingleMD5.h"
#import "MttUserBase.h"

@interface MttLoginReq : TarsObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(stUB,setStUB:)) MttUserBase* JV2_PROP_NM(r,0,stUB);
@property (nonatomic, retain, JV2_PROP_GS_V2(sOrigGUID,setSOrigGUID:)) NSData* JV2_PROP_NM(r,1,sOrigGUID);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCrypt,setVCrypt:)) NSData* JV2_PROP_NM(r,2,vCrypt);
@property (nonatomic, assign, JV2_PROP_GS_V2(iWidth,setIWidth:)) TarsInt32 JV2_PROP_NM(r,3,iWidth);
@property (nonatomic, assign, JV2_PROP_GS_V2(iHeight,setIHeight:)) TarsInt32 JV2_PROP_NM(r,4,iHeight);
@property (nonatomic, retain, JV2_PROP_GS_V2(sChannel,setSChannel:)) NSString* JV2_PROP_NM(o,5,sChannel);
@property (nonatomic, assign, JV2_PROP_GS_V2(eRelayProtoVer,setERelayProtoVer:)) MttERelayProtoVer JV2_PROP_NM(r,6,eRelayProtoVer);
@property (nonatomic, retain, JV2_PROP_GS_V2(sMark,setSMark:)) NSData* JV2_PROP_NM(o,7,sMark);
@property (nonatomic, assign, JV2_PROP_GS_V2(iVerifyId,setIVerifyId:)) TarsInt32 JV2_PROP_NM(o,8,iVerifyId);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSet,setVCharSet:)) NSData* JV2_PROP_NM(o,9,vCharSet);
@property (nonatomic, retain, JV2_PROP_GS_V2(vMidCharSet,setVMidCharSet:)) NSData* JV2_PROP_NM(o,10,vMidCharSet);
@property (nonatomic, retain, JV2_PROP_GS_V2(vBigCharSet,setVBigCharSet:)) NSData* JV2_PROP_NM(o,11,vBigCharSet);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetMD5,setVCharSetMD5:)) NSData* JV2_PROP_NM(o,12,vCharSetMD5);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetMD5Group,setVCharSetMD5Group:)) NSArray* JV2_PROP_EX(o,13,vCharSetMD5Group,VOMTTSTSingleMD5);
@property (nonatomic, assign, JV2_PROP_GS_V2(bHttpProxy,setBHttpProxy:)) TarsInt8 JV2_PROP_NM(o,14,bHttpProxy);
@property (nonatomic, assign, JV2_PROP_GS_V2(bCrashTag,setBCrashTag:)) TarsInt8 JV2_PROP_NM(o,15,bCrashTag);

@end
