/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttSTSingleMD5.h"
#import "MttUpdateRsp.h"
#import "MttVerifyRspExt.h"

@interface MttLoginRsp : TarsObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sGUID,setSGUID:)) NSData* JV2_PROP_NM(r,0,sGUID);
@property (nonatomic, retain, JV2_PROP_GS_V2(vAuth,setVAuth:)) NSData* JV2_PROP_NM(r,1,vAuth);
@property (nonatomic, assign, JV2_PROP_GS_V2(iTime,setITime:)) TarsInt32 JV2_PROP_NM(r,2,iTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(vProxyList,setVProxyList:)) NSArray* JV2_PROP_EX(r,3,vProxyList,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vRelayList,setVRelayList:)) NSArray* JV2_PROP_EX(r,4,vRelayList,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(stUpdateRsp,setStUpdateRsp:)) MttUpdateRsp* JV2_PROP_NM(r,5,stUpdateRsp);
@property (nonatomic, retain, JV2_PROP_GS_V2(stVerifyRspExt,setStVerifyRspExt:)) MttVerifyRspExt* JV2_PROP_NM(o,6,stVerifyRspExt);
@property (nonatomic, assign, JV2_PROP_GS_V2(iStatValue,setIStatValue:)) TarsInt32 JV2_PROP_NM(o,7,iStatValue);
@property (nonatomic, retain, JV2_PROP_GS_V2(vRelayHttpsList,setVRelayHttpsList:)) NSData* JV2_PROP_NM(o,8,vRelayHttpsList);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetKey,setVCharSetKey:)) NSData* JV2_PROP_NM(o,10,vCharSetKey);
@property (nonatomic, retain, JV2_PROP_GS_V2(vMidCharSetKey,setVMidCharSetKey:)) NSData* JV2_PROP_NM(o,11,vMidCharSetKey);
@property (nonatomic, retain, JV2_PROP_GS_V2(vBigCharSetKey,setVBigCharSetKey:)) NSData* JV2_PROP_NM(o,12,vBigCharSetKey);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCharSetMD5Group,setVCharSetMD5Group:)) NSArray* JV2_PROP_EX(o,13,vCharSetMD5Group,VOMTTSTSingleMD5);
@property (nonatomic, assign, JV2_PROP_GS_V2(iHttpProxySession,setIHttpProxySession:)) TarsInt32 JV2_PROP_NM(o,14,iHttpProxySession);
@property (nonatomic, retain, JV2_PROP_GS_V2(vQProxyList,setVQProxyList:)) NSArray* JV2_PROP_EX(o,15,vQProxyList,VONSString);
@property (nonatomic, assign, JV2_PROP_GS_V2(cProtocolFlag,setCProtocolFlag:)) TarsInt8 JV2_PROP_NM(o,16,cProtocolFlag);

@end
