/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttLoginReq.h"

@implementation MttLoginReq

@synthesize JV2_PROP_NM(r,0,stUB);
@synthesize JV2_PROP_NM(r,1,sOrigGUID);
@synthesize JV2_PROP_NM(r,2,vCrypt);
@synthesize JV2_PROP_NM(r,3,iWidth);
@synthesize JV2_PROP_NM(r,4,iHeight);
@synthesize JV2_PROP_NM(o,5,sChannel);
@synthesize JV2_PROP_NM(r,6,eRelayProtoVer);
@synthesize JV2_PROP_NM(o,7,sMark);
@synthesize JV2_PROP_NM(o,8,iVerifyId);
@synthesize JV2_PROP_NM(o,9,vCharSet);
@synthesize JV2_PROP_NM(o,10,vMidCharSet);
@synthesize JV2_PROP_NM(o,11,vBigCharSet);
@synthesize JV2_PROP_NM(o,12,vCharSetMD5);
@synthesize JV2_PROP_EX(o,13,vCharSetMD5Group,VOMTTSTSingleMD5);
@synthesize JV2_PROP_NM(o,14,bHttpProxy);
@synthesize JV2_PROP_NM(o,15,bCrashTag);

+ (void)initialize
{
    if (self == [MttLoginReq class]) {
        [MttSTSingleMD5 initialize];
        [MttUserBase initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(stUB) = [MttUserBase object];
        JV2_PROP(sOrigGUID) = DefaultTarsData;
        JV2_PROP(vCrypt) = DefaultTarsData;
        JV2_PROP(sChannel) = DefaultTarsString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(stUB) = nil;
    JV2_PROP(sOrigGUID) = nil;
    JV2_PROP(vCrypt) = nil;
    JV2_PROP(sChannel) = nil;
    JV2_PROP(sMark) = nil;
    JV2_PROP(vCharSet) = nil;
    JV2_PROP(vMidCharSet) = nil;
    JV2_PROP(vBigCharSet) = nil;
    JV2_PROP(vCharSetMD5) = nil;
    JV2_PROP(vCharSetMD5Group) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.LoginReq";
}

@end
