/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttMTTContentType.h"

#if TARSV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttMTTContentTypeHelper

+ (NSString *)etos:(MttMTTContentType)e
{
    switch(e){
        case MttMTTContentType_CT_DEFAULT: return @"MttMTTContentType_CT_DEFAULT";
        case MttMTTContentType_CT_NORMAL_HTML: return @"MttMTTContentType_CT_NORMAL_HTML";
        case MttMTTContentType_CT_SERIAL_DOM: return @"MttMTTContentType_CT_SERIAL_DOM";
        case MttMTTContentType_CT_WAP10: return @"MttMTTContentType_CT_WAP10";
        case MttMTTContentType_CT_RENDER_TREE: return @"MttMTTContentType_CT_RENDER_TREE";
        case MttMTTContentType_CT_IMG: return @"MttMTTContentType_CT_IMG";
        case MttMTTContentType_CT_THUMBNAIL: return @"MttMTTContentType_CT_THUMBNAIL";
        case MttMTTContentType_CT_THUMBNAIL_OPTIMIZED: return @"MttMTTContentType_CT_THUMBNAIL_OPTIMIZED";
        default: return @"";
    }
}

+ (MttMTTContentType)stoe:(NSString *)s
{
    if(isTarsEnumStringEqual(s, @"MttMTTContentType_CT_DEFAULT")) return MttMTTContentType_CT_DEFAULT;
    if(isTarsEnumStringEqual(s, @"MttMTTContentType_CT_NORMAL_HTML")) return MttMTTContentType_CT_NORMAL_HTML;
    if(isTarsEnumStringEqual(s, @"MttMTTContentType_CT_SERIAL_DOM")) return MttMTTContentType_CT_SERIAL_DOM;
    if(isTarsEnumStringEqual(s, @"MttMTTContentType_CT_WAP10")) return MttMTTContentType_CT_WAP10;
    if(isTarsEnumStringEqual(s, @"MttMTTContentType_CT_RENDER_TREE")) return MttMTTContentType_CT_RENDER_TREE;
    if(isTarsEnumStringEqual(s, @"MttMTTContentType_CT_IMG")) return MttMTTContentType_CT_IMG;
    if(isTarsEnumStringEqual(s, @"MttMTTContentType_CT_THUMBNAIL")) return MttMTTContentType_CT_THUMBNAIL;
    if(isTarsEnumStringEqual(s, @"MttMTTContentType_CT_THUMBNAIL_OPTIMIZED")) return MttMTTContentType_CT_THUMBNAIL_OPTIMIZED;
    return NSIntegerMin;
}

@end

#endif
