/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"
#import "MttMethod.h"

#if TARSV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation MttMethodHelper

+ (NSString *)etos:(MttMethod)e
{
    switch(e){
        case MttMethod_GET: return @"MttMethod_GET";
        case MttMethod_POST: return @"MttMethod_POST";
        case MttMethod_CONNECT: return @"MttMethod_CONNECT";
        case MttMethod_CONNECTDATA: return @"MttMethod_CONNECTDATA";
        default: return @"";
    }
}

+ (MttMethod)stoe:(NSString *)s
{
    if(isTarsEnumStringEqual(s, @"MttMethod_GET")) return MttMethod_GET;
    if(isTarsEnumStringEqual(s, @"MttMethod_POST")) return MttMethod_POST;
    if(isTarsEnumStringEqual(s, @"MttMethod_CONNECT")) return MttMethod_CONNECT;
    if(isTarsEnumStringEqual(s, @"MttMethod_CONNECTDATA")) return MttMethod_CONNECTDATA;
    return NSIntegerMin;
}

@end

#endif
