/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"

@interface MttPerformanceInfo : TarsObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sDevice,setSDevice:)) NSString* JV2_PROP_NM(o,0,sDevice);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUrl,setSUrl:)) NSString* JV2_PROP_NM(o,1,sUrl);
@property (nonatomic, retain, JV2_PROP_GS_V2(sAPN,setSAPN:)) NSString* JV2_PROP_NM(o,2,sAPN);
@property (nonatomic, assign, JV2_PROP_GS_V2(iProxyType,setIProxyType:)) TarsInt8 JV2_PROP_NM(o,3,iProxyType);
@property (nonatomic, assign, JV2_PROP_GS_V2(iTotalTime,setITotalTime:)) TarsInt32 JV2_PROP_NM(o,4,iTotalTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(iMainResDownloadTime,setIMainResDownloadTime:)) TarsInt32 JV2_PROP_NM(o,5,iMainResDownloadTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(iAvgDNSTime,setIAvgDNSTime:)) TarsInt32 JV2_PROP_NM(o,6,iAvgDNSTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(iAvgConnectTime,setIAvgConnectTime:)) TarsInt32 JV2_PROP_NM(o,7,iAvgConnectTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(iAvgWaitRspTime,setIAvgWaitRspTime:)) TarsInt32 JV2_PROP_NM(o,8,iAvgWaitRspTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(iAvgSpeed,setIAvgSpeed:)) TarsInt32 JV2_PROP_NM(o,9,iAvgSpeed);

@end
