/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttRelayPageReq.h"

@implementation MttRelayPageReq

@synthesize JV2_PROP_NM(r,0,stUB);
@synthesize JV2_PROP_NM(r,1,eMethod);
@synthesize JV2_PROP_NM(r,2,sUrl);
@synthesize JV2_PROP_NM(o,3,sReferer);
@synthesize JV2_PROP_NM(r,4,sExtraHeader);
@synthesize JV2_PROP_NM(o,5,vPostData);
@synthesize JV2_PROP_NM(r,6,sPageOrigEncode);
@synthesize JV2_PROP_NM(r,7,iPageSizeKB);
@synthesize JV2_PROP_EX(r,8,vLocalPicHash,VONSNumber);
@synthesize JV2_PROP_NM(r,9,eQualityType);
@synthesize JV2_PROP_NM(r,10,iWidth);
@synthesize JV2_PROP_NM(r,11,iHeight);
@synthesize JV2_PROP_NM(r,12,sTSpeed);
@synthesize JV2_PROP_NM(o,13,stImgPolicy);
@synthesize JV2_PROP_NM(o,14,stJSInfo);

+ (void)initialize
{
    if (self == [MttRelayPageReq class]) {
        [MttSTImagePolicy initialize];
        [MttSTJSInfo initialize];
        [MttSTSpeedStatis initialize];
        [MttUserBase initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(stUB) = [MttUserBase object];
        JV2_PROP(sUrl) = DefaultTarsString;
        JV2_PROP(sReferer) = DefaultTarsString;
        JV2_PROP(sExtraHeader) = DefaultTarsString;
        JV2_PROP(sPageOrigEncode) = DefaultTarsString;
        JV2_PROP(vLocalPicHash) = DefaultTarsArray;
        JV2_PROP(sTSpeed) = [MttSTSpeedStatis object];
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(stUB) = nil;
    JV2_PROP(sUrl) = nil;
    JV2_PROP(sReferer) = nil;
    JV2_PROP(sExtraHeader) = nil;
    JV2_PROP(vPostData) = nil;
    JV2_PROP(sPageOrigEncode) = nil;
    JV2_PROP(vLocalPicHash) = nil;
    JV2_PROP(sTSpeed) = nil;
    JV2_PROP(stImgPolicy) = nil;
    JV2_PROP(stJSInfo) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.RelayPageReq";
}

@end
