/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttSearchInfo.h"

@implementation MttSearchInfo

@synthesize JV2_PROP_NM(r,0,sShortName);
@synthesize JV2_PROP_NM(r,1,sAllName);
@synthesize JV2_PROP_NM(r,2,sHref);
@synthesize JV2_PROP_NM(r,3,sImageName);
@synthesize JV2_PROP_NM(r,4,sEncodeType);
@synthesize JV2_PROP_NM(o,5,iDefault);
@synthesize JV2_PROP_NM(o,6,sSearchName);
@synthesize JV2_PROP_NM(o,7,sImageData);

+ (void)initialize
{
    if (self == [MttSearchInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sShortName) = DefaultTarsString;
        JV2_PROP(sAllName) = DefaultTarsString;
        JV2_PROP(sHref) = DefaultTarsString;
        JV2_PROP(sImageName) = DefaultTarsString;
        JV2_PROP(sEncodeType) = DefaultTarsString;
        JV2_PROP(sSearchName) = DefaultTarsString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sShortName) = nil;
    JV2_PROP(sAllName) = nil;
    JV2_PROP(sHref) = nil;
    JV2_PROP(sImageName) = nil;
    JV2_PROP(sEncodeType) = nil;
    JV2_PROP(sSearchName) = nil;
    JV2_PROP(sImageData) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.SearchInfo";
}

@end
