/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttStaticConfigReq.h"

@implementation MttStaticConfigReq

@synthesize JV2_PROP_NM(r,0,iKeywordTime);
@synthesize JV2_PROP_NM(r,1,iDomainTime);
@synthesize JV2_PROP_NM(r,2,iPluginTime);
@synthesize JV2_PROP_NM(o,3,iPicTime);
@synthesize JV2_PROP_NM(o,4,vDomainReqType);
@synthesize JV2_PROP_NM(o,5,iDomainVer);
@synthesize JV2_PROP_NM(o,6,iNewDomainTime);
@synthesize JV2_PROP_NM(o,7,iConfTime);
@synthesize JV2_PROP_NM(o,8,iIconTime);

+ (void)initialize
{
    if (self == [MttStaticConfigReq class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(iKeywordTime) = -1;
        JV2_PROP(iDomainTime) = -1;
        JV2_PROP(iPluginTime) = -1;
        JV2_PROP(iPicTime) = -1;
        JV2_PROP(iNewDomainTime) = -1;
        JV2_PROP(iConfTime) = -1;
        JV2_PROP(iIconTime) = -1;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(vDomainReqType) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.StaticConfigReq";
}

@end
