/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"

@interface MttTipPushRsp : TarsObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iId,setIId:)) TarsInt32 JV2_PROP_NM(o,0,iId);
@property (nonatomic, assign, JV2_PROP_GS_V2(iStype,setIStype:)) TarsInt32 JV2_PROP_NM(o,1,iStype);
@property (nonatomic, assign, JV2_PROP_GS_V2(iNextTime,setINextTime:)) TarsInt32 JV2_PROP_NM(o,2,iNextTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(sContent,setSContent:)) NSString* JV2_PROP_NM(o,3,sContent);
@property (nonatomic, retain, JV2_PROP_GS_V2(sImgName,setSImgName:)) NSString* JV2_PROP_NM(o,4,sImgName);
@property (nonatomic, retain, JV2_PROP_GS_V2(vImg,setVImg:)) NSData* JV2_PROP_NM(o,5,vImg);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUrl,setSUrl:)) NSString* JV2_PROP_NM(o,6,sUrl);

@end
