/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttUserBase.h"

@implementation MttUserBase

@synthesize JV2_PROP_NM(r,0,sIMEI);
@synthesize JV2_PROP_NM(r,1,sGUID);
@synthesize JV2_PROP_NM(r,2,sQUA);
@synthesize JV2_PROP_NM(r,3,sLC);
@synthesize JV2_PROP_NM(r,4,sCellphone);
@synthesize JV2_PROP_NM(r,5,sUin);
@synthesize JV2_PROP_NM(o,6,sCellid);
@synthesize JV2_PROP_NM(o,7,iServerVer);
@synthesize JV2_PROP_NM(o,8,bSave);
@synthesize JV2_PROP_NM(o,9,sChannel);
@synthesize JV2_PROP_NM(o,10,sLAC);
@synthesize JV2_PROP_NM(o,11,sUA);
@synthesize JV2_PROP_NM(o,12,iLanguageType);
@synthesize JV2_PROP_NM(o,13,iMCC);
@synthesize JV2_PROP_NM(o,14,iMNC);
@synthesize JV2_PROP_NM(o,15,sAPN);
@synthesize JV2_PROP_NM(o,16,sCellNumber);
@synthesize JV2_PROP_NM(o,17,sMac);

+ (void)initialize
{
    if (self == [MttUserBase class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sIMEI) = DefaultTarsString;
        JV2_PROP(sGUID) = DefaultTarsData;
        JV2_PROP(sQUA) = DefaultTarsString;
        JV2_PROP(sLC) = DefaultTarsString;
        JV2_PROP(sCellphone) = DefaultTarsString;
        JV2_PROP(sUin) = DefaultTarsString;
        JV2_PROP(sCellid) = DefaultTarsString;
        JV2_PROP(iServerVer) = 1;
        JV2_PROP(bSave) = YES;
        JV2_PROP(sChannel) = DefaultTarsString;
        JV2_PROP(sLAC) = DefaultTarsString;
        JV2_PROP(sUA) = DefaultTarsString;
        JV2_PROP(iLanguageType) = 200;
        JV2_PROP(sAPN) = DefaultTarsString;
        JV2_PROP(sCellNumber) = DefaultTarsString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sIMEI) = nil;
    JV2_PROP(sGUID) = nil;
    JV2_PROP(sQUA) = nil;
    JV2_PROP(sLC) = nil;
    JV2_PROP(sCellphone) = nil;
    JV2_PROP(sUin) = nil;
    JV2_PROP(sCellid) = nil;
    JV2_PROP(sChannel) = nil;
    JV2_PROP(sLAC) = nil;
    JV2_PROP(sUA) = nil;
    JV2_PROP(sAPN) = nil;
    JV2_PROP(sCellNumber) = nil;
    JV2_PROP(sMac) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.UserBase";
}

@end
