/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "MttWeatherInfo.h"

@implementation MttWeatherInfo

@synthesize JV2_PROP_NM(o,0,sDate);
@synthesize JV2_PROP_NM(o,1,sWeek);
@synthesize JV2_PROP_NM(o,2,iDWeaIndex);
@synthesize JV2_PROP_NM(o,3,sDweather);
@synthesize JV2_PROP_NM(o,4,iMaxT);
@synthesize JV2_PROP_NM(o,5,iMinT);
@synthesize JV2_PROP_NM(o,7,bWeatherOther);
@synthesize JV2_PROP_NM(o,8,iCurrentT);
@synthesize JV2_PROP_NM(o,9,sWind);
@synthesize JV2_PROP_NM(o,10,sWindPower);
@synthesize JV2_PROP_NM(o,11,sMoreUrl);

+ (void)initialize
{
    if (self == [MttWeatherInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sDate) = DefaultTarsString;
        JV2_PROP(sWeek) = DefaultTarsString;
        JV2_PROP(sDweather) = DefaultTarsString;
        JV2_PROP(sWind) = DefaultTarsString;
        JV2_PROP(sWindPower) = DefaultTarsString;
        JV2_PROP(sMoreUrl) = DefaultTarsString;
    }
    return self;
}

- (void)dealloc
{
    JV2_PROP(sDate) = nil;
    JV2_PROP(sWeek) = nil;
    JV2_PROP(sDweather) = nil;
    JV2_PROP(sWind) = nil;
    JV2_PROP(sWindPower) = nil;
    JV2_PROP(sMoreUrl) = nil;
    [super dealloc];
}

+ (NSString*)tarsType
{
    return @"MTT.WeatherInfo";
}

@end
