/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */

// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/tars/upload/renjunyi/MTT.tars'
// **********************************************************************

#import "TarsObjectV2.h"

@interface MttWeatherInfo : TarsObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sDate,setSDate:)) NSString* JV2_PROP_NM(o,0,sDate);
@property (nonatomic, retain, JV2_PROP_GS_V2(sWeek,setSWeek:)) NSString* JV2_PROP_NM(o,1,sWeek);
@property (nonatomic, assign, JV2_PROP_GS_V2(iDWeaIndex,setIDWeaIndex:)) TarsInt32 JV2_PROP_NM(o,2,iDWeaIndex);
@property (nonatomic, retain, JV2_PROP_GS_V2(sDweather,setSDweather:)) NSString* JV2_PROP_NM(o,3,sDweather);
@property (nonatomic, assign, JV2_PROP_GS_V2(iMaxT,setIMaxT:)) TarsInt32 JV2_PROP_NM(o,4,iMaxT);
@property (nonatomic, assign, JV2_PROP_GS_V2(iMinT,setIMinT:)) TarsInt32 JV2_PROP_NM(o,5,iMinT);
@property (nonatomic, assign, JV2_PROP_GS_V2(bWeatherOther,setBWeatherOther:)) TarsInt8 JV2_PROP_NM(o,7,bWeatherOther);
@property (nonatomic, assign, JV2_PROP_GS_V2(iCurrentT,setICurrentT:)) TarsInt32 JV2_PROP_NM(o,8,iCurrentT);
@property (nonatomic, retain, JV2_PROP_GS_V2(sWind,setSWind:)) NSString* JV2_PROP_NM(o,9,sWind);
@property (nonatomic, retain, JV2_PROP_GS_V2(sWindPower,setSWindPower:)) NSString* JV2_PROP_NM(o,10,sWindPower);
@property (nonatomic, retain, JV2_PROP_GS_V2(sMoreUrl,setSMoreUrl:)) NSString* JV2_PROP_NM(o,11,sMoreUrl);

@end
