<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__login.proto

namespace Proto\yb_account\account__login;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>in</code>
 */
class in extends \Google\Protobuf\Internal\Message
{
    /**
     * 角色
     *
     * Generated from protobuf field <code>int32 role = 1;</code>
     */
    private $role = 0;
    /**
     *电话
     *
     * Generated from protobuf field <code>string phone = 2;</code>
     */
    private $phone = '';
    /**
     *密码 md5(md5(passwd)."&#64;leo") 
     *
     * Generated from protobuf field <code>string passwd = 3;</code>
     */
    private $passwd = '';

    public function __construct() {
        \GPBMetadata\YbAccount\AccountLogin::initOnce();
        parent::__construct();
    }

    /**
     * 角色
     *
     * Generated from protobuf field <code>int32 role = 1;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * 角色
     *
     * Generated from protobuf field <code>int32 role = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkInt32($var);
        $this->role = $var;

        return $this;
    }

    /**
     *电话
     *
     * Generated from protobuf field <code>string phone = 2;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     *电话
     *
     * Generated from protobuf field <code>string phone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     *密码 md5(md5(passwd)."&#64;leo") 
     *
     * Generated from protobuf field <code>string passwd = 3;</code>
     * @return string
     */
    public function getPasswd()
    {
        return $this->passwd;
    }

    /**
     *密码 md5(md5(passwd)."&#64;leo") 
     *
     * Generated from protobuf field <code>string passwd = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPasswd($var)
    {
        GPBUtil::checkString($var, True);
        $this->passwd = $var;

        return $this;
    }

}

