
#-----------------------------------------------------------------------

APP       := Test
TARGET    := utilTest
#CFLAGS    := O2
CONFIG    := 
#STRIP_FLAG:= N
TARS_SSL := 1

INCLUDE   +=  -I/usr/local/tars/cpp/include
LIB       += 
LOCAL_SRC   +=  
#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
