<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__add_small_class_order_info.proto

namespace GPBMetadata\YbAccount;

class AccountAddSmallClassOrderInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4010a3479625f6163636f756e742f6163636f756e745f5f6164645f73" .
            "6d616c6c5f636c6173735f6f726465725f696e666f2e70726f746f22330a" .
            "02696e120d0a057072696365180120012805120e0a067573657269641802" .
            "20012805120e0a0672656d61726b18032001280922160a036f7574120f0a" .
            "076f7264657269641801200128094237ca023450726f746f5c79625f6163" .
            "636f756e745c6163636f756e745f5f6164645f736d616c6c5f636c617373" .
            "5f6f726465725f696e666f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

