<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__reset_passwd.proto

namespace GPBMetadata\YbAccount;

class AccountResetPasswd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\YbAccount\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95010a2679625f6163636f756e742f6163636f756e745f5f7265736574" .
            "5f7061737377642e70726f746f22310a02696e120c0a04726f6c65180120" .
            "012805120d0a0570686f6e65180220012809120e0a067061737377641803" .
            "2001280922050a036f75744229ca022650726f746f5c79625f6163636f75" .
            "6e745c6163636f756e745f5f72657365745f706173737764620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

