<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__register.proto

namespace GPBMetadata\YbAccount;

class AccountRegister
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe010a2279625f6163636f756e742f6163636f756e745f5f7265676973" .
            "7465722e70726f746f22560a02696e120c0a04726f6c6518012001280512" .
            "0d0a0570686f6e65180220012809120e0a06706173737764180320012809" .
            "120e0a067265675f697018042001280912130a0b7265675f6368616e6e65" .
            "6c18052001280922110a036f7574120a0a0269641801200128054225ca02" .
            "2250726f746f5c79625f6163636f756e745c6163636f756e745f5f726567" .
            "6973746572620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

