<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/common.proto

namespace GPBMetadata\YbAccount;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7f0a1779625f6163636f756e742f636f6d6d6f6e2e70726f746f120663" .
            "6f6d6d6f6e22380a09757365725f6974656d120c0a04726f6c6518012001" .
            "2805120d0a0570686f6e65180220012809120e0a06706173737764180320" .
            "012809421aca021750726f746f5c79625f6163636f756e745c636f6d6d6f" .
            "6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

