<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/error.proto

namespace GPBMetadata\YbAccount;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5020a1679625f6163636f756e742f6572726f722e70726f746f120565" .
            "72726f722af0010a0a656e756d5f6572726f72120c0a084552525f535543" .
            "431000120f0a0a4552525f53595354454d10ea0712150a104552525f494e" .
            "5f50524f544f5f4c454e10e80712160a114552525f4f55545f50524f544f" .
            "5f4c454e10f207120f0a0a4552525f50415353574410b91712140a0f4552" .
            "525f555345525f4e4f46494e4410ba1712150a104552525f555345525f45" .
            "58495354454410bb17120e0a094552525f50484f4e4510bc17120d0a0845" .
            "52525f434f444510bd17121a0a154552525f5041535357445f434f4e5349" .
            "5354454e5410be17121b0a164552525f5041535357445f52455345545f45" .
            "52524f5210bf174219ca021650726f746f5c79625f6163636f756e745c65" .
            "72726f72620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

