<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__test.proto

namespace GPBMetadata\YbAccount;

class AccountTest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\YbAccount\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a87020a1e79625f6163636f756e742f6163636f756e745f5f746573742e" .
            "70726f746f22560a02696e120c0a04726f6c65180120012805120d0a0570" .
            "686f6e65180220012809120e0a06706173737764180320012809120e0a06" .
            "7265675f697018042001280912130a0b7265675f6368616e6e656c180520" .
            "01280922620a036f7574120a0a02696418012001280512240a0975736572" .
            "5f696e666f18022001280b32112e636f6d6d6f6e2e757365725f6974656d" .
            "12290a0e757365725f696e666f5f6c69737418032003280b32112e636f6d" .
            "6d6f6e2e757365725f6974656d4221ca021e50726f746f5c79625f616363" .
            "6f756e745c6163636f756e745f5f74657374620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

