<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__login.proto

namespace GPBMetadata\YbAccount;

class AccountLogin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\YbAccount\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9010a1f79625f6163636f756e742f6163636f756e745f5f6c6f67696e" .
            "2e70726f746f22310a02696e120c0a04726f6c65180120012805120d0a05" .
            "70686f6e65180220012809120e0a0670617373776418032001280922370a" .
            "036f7574120a0a02696418012001280512120a0a7265674368616e6e656c" .
            "18022001280912100a0877784f70656e69641803200128094222ca021f50" .
            "726f746f5c79625f6163636f756e745c6163636f756e745f5f6c6f67696e" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

