<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__get_userid.proto

namespace GPBMetadata\YbAccount;

class AccountGetUserid
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8d010a2479625f6163636f756e742f6163636f756e745f5f6765745f75" .
            "73657269642e70726f746f22210a02696e120c0a04726f6c651801200128" .
            "05120d0a0570686f6e6518022001280922110a036f7574120a0a02696418" .
            "01200128054227ca022450726f746f5c79625f6163636f756e745c616363" .
            "6f756e745f5f6765745f757365726964620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

