<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__refund_small_class_order_info.proto

namespace GPBMetadata\YbAccount;

class AccountRefundSmallClassOrderInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae0010a3779625f6163636f756e742f6163636f756e745f5f726566756e" .
            "645f736d616c6c5f636c6173735f6f726465725f696e666f2e70726f746f" .
            "225a0a02696e12120a0a636f6e74726163746964180120012809120d0a05" .
            "7072696365180220012805120e0a0672656d61726b180320012809120c0a" .
            "046e616d6518042001280912130a0b7061795f6163636f756e7418052001" .
            "280922050a036f7574423aca023750726f746f5c79625f6163636f756e74" .
            "5c6163636f756e745f5f726566756e645f736d616c6c5f636c6173735f6f" .
            "726465725f696e666f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

