<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__student_register_backstage.proto

namespace GPBMetadata\YbAccount;

class AccountStudentRegisterBackstage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9f010a3479625f6163636f756e742f6163636f756e745f5f7374756465" .
            "6e745f72656769737465725f6261636b73746167652e70726f746f22130a" .
            "02696e120d0a0570686f6e6518012001280922110a036f7574120a0a0269" .
            "641801200128054237ca023450726f746f5c79625f6163636f756e745c61" .
            "63636f756e745f5f73747564656e745f72656769737465725f6261636b73" .
            "74616765620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

