<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/account__send_verification_code_for_change_passwd.proto

namespace GPBMetadata\YbAccount;

class AccountSendVerificationCodeForChangePasswd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\YbAccount\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aeb010a4279625f6163636f756e742f6163636f756e745f5f73656e645f" .
            "766572696669636174696f6e5f636f64655f666f725f6368616e67655f70" .
            "61737377642e70726f746f22210a02696e120c0a04726f6c651801200128" .
            "05120d0a0570686f6e6518022001280922330a036f757412110a096d7367" .
            "5f696e64657818012001280912190a11766572696669636174696f6e5f63" .
            "6f64651802200128094245ca024250726f746f5c79625f6163636f756e74" .
            "5c6163636f756e745f5f73656e645f766572696669636174696f6e5f636f" .
            "64655f666f725f6368616e67655f706173737764620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

