
#-----------------------------------------------------------------------

APP       := TestApp
TARGET    := TestHelloServer
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------

include /home/tarsproto/TestApp/HelloServer/HelloServer.mk
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
