
#-----------------------------------------------------------------------

APP       := TestApp
TARGET    := TestHelloServer
CONFIG    := 
CFLAGS    := --std=c++0x
STRIP_FLAG:= N

INCLUDE   += -I../ 
LIB       += 

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
