// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

var tars = require('./NodeSecond.js').tars;
var TestServer = require("../../demo.1/client.node.proxy/NodeTarsProxy.js").tars;
module.exports.tars = tars;

tars.NodeSecondImp.prototype.initialize = function ( ) {
    //TODO::
    //server通过initialize或者在tars容器中通过start启动时，会默认初始化一个客户端通信器
    this.TestProxy = this.application.communicator.stringToProxy(TestServer.NodeTarsProxy, "TARS.NodeTarsServer.NodeTarsObj@tcp -h 127.0.0.1 -p 14002 -t 10000");
}

tars.NodeSecondImp.prototype.test = function (current) {
    //TODO::

}

tars.NodeSecondImp.prototype.yourName = function (current, sName, sUserName) {
    //TODO::
    console.log("i'm proxy server,yourName:", sName," i will send yourName to real server: demo.1/server.node.1");
    this.TestProxy.getUsrName(sName).then(function (result) {
        current.sendResponse("success", result.response.arguments.sValue1);
    })
}


