<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb_account/error.proto

namespace Proto\yb_account\error;

/**
 * Protobuf enum <code>Error\Enum_error</code>
 */
class enum_error
{
    /**
     *成功
     *
     * Generated from protobuf enum <code>ERR_SUCC = 0;</code>
     */
    const ERR_SUCC = 0;
    /**
     *系统出错
     *
     * Generated from protobuf enum <code>ERR_SYSTEM = 1002;</code>
     */
    const ERR_SYSTEM = 1002;
    /**
     *报文长度长度不对(IN)
     *
     * Generated from protobuf enum <code>ERR_IN_PROTO_LEN = 1000;</code>
     */
    const ERR_IN_PROTO_LEN = 1000;
    /**
     *报文长度长度不对(OUT)
     *
     * Generated from protobuf enum <code>ERR_OUT_PROTO_LEN = 1010;</code>
     */
    const ERR_OUT_PROTO_LEN = 1010;
    /**
     *密码出错
     *
     * Generated from protobuf enum <code>ERR_PASSWD = 3001;</code>
     */
    const ERR_PASSWD = 3001;
    /**
     *用户不存在
     *
     * Generated from protobuf enum <code>ERR_USER_NOFIND = 3002;</code>
     */
    const ERR_USER_NOFIND = 3002;
    /**
     *用户已经存在
     *
     * Generated from protobuf enum <code>ERR_USER_EXISTED = 3003;</code>
     */
    const ERR_USER_EXISTED = 3003;
    /**
     *手机号异常
     *
     * Generated from protobuf enum <code>ERR_PHONE = 3004;</code>
     */
    const ERR_PHONE = 3004;
    /**
     *验证码错误
     *
     * Generated from protobuf enum <code>ERR_CODE = 3005;</code>
     */
    const ERR_CODE = 3005;
    /**
     *两次密码不一致
     *
     * Generated from protobuf enum <code>ERR_PASSWD_CONSISTENT = 3006;</code>
     */
    const ERR_PASSWD_CONSISTENT = 3006;
    /**
     *修改密码失败
     *
     * Generated from protobuf enum <code>ERR_PASSWD_RESET_ERROR = 3007;</code>
     */
    const ERR_PASSWD_RESET_ERROR = 3007;
}

