
#-----------------------------------------------------------------------

APP       := TestApp
TARGET    := TestProxy
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------

include /home/tarsproto/TestApp/ProxyServer/ProxyServer.mk
include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
