name: deploy-latest-framework-docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: docker login
        run: |
          docker login -u ${{ secrets.name }} -p ${{ secrets.pass }}
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: deploy docker
        run: |
          echo $GITHUB_SHA
          ./tars-latest-deploy-framework.sh true
