name: deploy-framework-docker

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-20.04 
    steps:
      - name: docker login
        run: |
          docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} 
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: deploy docker
        run: |
          echo $GITHUB_SHA
          ./tars-deploy-framework.sh ${{ steps.get_version.outputs.VERSION }} true
